base_url = "https://arkovyx.github.io"
theme = "ametrine"
compile_sass = true
build_search_index = true

title = "arkovyx"
description = "Personal website of arkovyx"
author = "arkovyx"

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
taxonomies = []

[markdown]
render_emoji = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
logo_text = "~/arkovyx"
enable_search = true
default_theme = "dark"

list_pages = false
recent = false

accent_color = ["hsl(15, 40%, 30%)", "hsl(40, 50%, 50%)"]

header_nav = [
    { url = "/", name_en = "~/home" }
]

[extra.author]
name = "Arkovyx"
avatar = "1.jpg"

[extra.meta]
favicon = "2.jpg"
apple_touch_icon = "2.jpg"

[extra.footer]
copyright = "© 2026 Arkovyx · All rights reserved."
show_powered_by = true
show_timestamp = true
socials = [
    { url = "https://github.com/arkovyx", icon = "github"},
    { url = "https://arkovyx.github.io/keylocity", icon = "speedtest"},
    { url = "https://instagram.com/arkovyx", icon = "instagram"},
]

[extra.nav]
icon = "2.jpg"
links = [
    { name = "writing", category = [
        { url = "/blog", name = "Blog", icon = "newspaper-clipping" },
        { url = "/nanolog", name = "Nanolog", icon = "note-pencil" }
    ]},
    { name = "misc", category = [
        { url = "/contact", name = "Contact", icon = "user" }
    ]}
]
